### PR TITLE
Fix bug and some improvements to the library

### PR DESCRIPTION
**Pull request by RicCPT**
## Allow another port when download firmware
Allow use another port when download firmware, current version have port 80 hardcoded.

## Debug EEPROM (read/Write)
Show in debug what is read/write in EEPROM.
Can enable debug puting this code "**`#define DEBUG_EEPROM_CONFIG true`**" in the user schetch.

## Write to EEPROM only if config change
**_BUG:_** the current version always writes to the EEPROM when boots, because the field "**`_setPreSet`**" is always **`true`** when boot.
With this code only writes to EEPROM when config is changed.

## Only initialize fields in constructor
Do not execute complex code in constructor (ex: readConfig), the execution of this code can't be debuged there, because the debug flag is not yet set.
The execution of this code must be delayed until call **`begin `** method.

#
Thanks for this great library :)
Best regards,

Ricardo Carvalho
ricardocarvalho@c-core.org

### CODE REVIEW

**Comment by Onno-Dirkzwager** [comment]
Hi Ricardo,
thanks for the Pull request. We will have to dive in deaper at a later moment, but a first glance we like the proposed changes.

First question: can you redo the pull request and address it to the develop branch? This way we can keep developing while new users can use the tested master.

Second: why do you want to change the port? Perhaps for personal use?

We have some changes of our own and together with yours we want to release 1.0.7 somewhere next week. (this also gets pushed to the Arduino lib manager)

Regards
IOTAppStory.com

**Comment by RicCPT** [comment]
Hi,

> ...can you redo the pull request and address it to the develop branch?

I changed the pull request to the develop brach as requested :)


> why do you want to change the port? Perhaps for personal use?
Yes for personal use and to allow redirect traffic from an internal server (uses a port other than 80) to the internet.

Best Regards,
Ricardo Carvalho

**Comment by Onno-Dirkzwager** [comment]
Thankyou Ricardo, I hope to merge it this week together with some other updates.

**Comment by Onno-Dirkzwager** [comment]
Hi Ricardo,
we are having problems with your changes. There have been a lot of changes since Sep but all of your code looks intact. I would like to ask you for your opinion:

- Debug EEPROM (read/write)
- Write to the EEPROM only if config value change 

Using the preSetConfig() do not seem to work. When using IAS.preSetConfig("VirginSoil-Full"); for example does not change the boardName to VirginSoil-Full.

It looks like:
	if (!_configReaded) {
		readConfig();
	}
Overwrites any changes before actually saving it to eeprom.

Any help is welcome.

**Pull request merged**
